name: Hello World API CI

on:
  push:
    branches: [main]

env:
  AR_IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.AR_REPO_NAME }}/hello-world-api

jobs:
  ci:
    permissions:
      id-token: "write"
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        id: lint
        continue-on-error: true
        run: npm run lint

      - name: Run lint:fix if lint failed
        if: steps.lint.outcome == 'failure'
        run: npm run lint:fix # Simulate linting errors fix

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: colintran2205/hello-world-api

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk.sarif

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@main"
        with:
          version: ">= 363.0.0"

      - name: Configure Docker for AR
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --project=${{ secrets.GCP_PROJECT_ID }}

      - name: "Extract Version from package.json"
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: "Define Image Tags"
        id: image_tags
        run: |
          VERSION_TAG="${{ env.AR_IMAGE }}:${{ steps.get_version.outputs.version }}"
          LATEST_TAG="${{ env.AR_IMAGE }}:latest"
          echo "version_tag=${VERSION_TAG}" >> $GITHUB_OUTPUT
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: "Build Docker Image"
        run: |
          docker build \
            --tag ${{ steps.image_tags.outputs.version_tag }} \
            --tag ${{ steps.image_tags.outputs.latest_tag }} \
            .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.image_tags.outputs.latest_tag }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif

      - name: "Push Docker Image to Artifact Registry"
        run: |
          docker push ${{ steps.image_tags.outputs.version_tag }}
          docker push ${{ steps.image_tags.outputs.latest_tag }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"
    env:
      IMAGE_NAME: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.AR_REPO_NAME }}/${{ secrets.CLOUDRUN_SERVICE_NAME }}:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@main"
        with:
          version: ">= 363.0.0"

      - name: Google Cloud Run deployment
        run: |
          gcloud run deploy ${{ secrets.CLOUDRUN_SERVICE_NAME }} \
            --image="${{ env.AR_IMAGE }}:latest" \
            --platform=managed \
            --allow-unauthenticated \
            --port="3000" \
            --liveness-probe=httpGet.path=/health,timeoutSeconds=10,httpGet.port=3000 \
            --cpu=1 --memory="128Mi" \
            --min-instances=1 --max-instances=5 \
            --concurrency=1\
            --set-env-vars="NODE_ENV=production" \
            --region=${{ secrets.GCP_REGION }}

      - name: Route traffic to latest revision
        run: |
          gcloud run services update-traffic ${{ secrets.CLOUDRUN_SERVICE_NAME }} \
            --region=${{ secrets.GCP_REGION }} \
            --to-latest

      - name: Get Service URL
        id: service-url
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ secrets.CLOUDRUN_SERVICE_NAME }} --region=${{ secrets.GCP_REGION }} --format="value(status.url)")
          echo "SERVICE_URL=${SERVICE_URL}" >> $GITHUB_OUTPUT
          echo "Service deployed at: ${SERVICE_URL}"

      - name: Health Check
        run: |
          sleep 30

          # Test the health endpoint
          curl -f "${{ steps.service-url.outputs.SERVICE_URL }}" || exit 1
          echo "Health check passed!"

  # Rollback Job (Manual trigger only)
  rollback:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@main"
        with:
          version: ">= 363.0.0"

      - name: List revisions
        run: |
          echo "Available revisions:"
          gcloud run revisions list --service=${{ secrets.CLOUDRUN_SERVICE_NAME }} --region=${{ secrets.GCP_REGION }}

      - name: Rollback instructions
        run: |
          echo "To rollback manually, run:"
          echo "gcloud run services update-traffic ${{ secrets.CLOUDRUN_SERVICE_NAME }} --to-revisions=REVISION-NAME=100 --region=${{ secrets.GCP_REGION }}"
          echo ""
          echo "To rollback to previous revision:"
          PREVIOUS_REVISION=$(gcloud run revisions list --service=${{ secrets.CLOUDRUN_SERVICE_NAME }} --region=${{ secrets.GCP_REGION }} --format="value(metadata.name)" --limit=2 | tail -n 1)
          echo "gcloud run services update-traffic ${{ secrets.CLOUDRUN_SERVICE_NAME }} --to-revisions=${PREVIOUS_REVISION}=100 --region=${{ secrets.GCP_REGION }}"
